import type { PipelineNode, PipelineLink } from "@/lib/types";

/**
 * The living pipeline — the hero visualization. Nodes and links are pure
 * data: reposition, add or remove stages here and the canvas re-renders,
 * packets and all. Coordinates live in a 1000 x 520 viewBox.
 */
export const pipelineNodes: PipelineNode[] = [
  {
    id: "src-api",
    label: "APIs",
    sublabel: "external systems",
    kind: "source",
    x: 70,
    y: 100,
    description: "Third-party and internal APIs feeding raw events into the platform.",
    tech: ["REST", "JSON", "Webhooks"],
  },
  {
    id: "src-db",
    label: "DATABASES",
    sublabel: "operational stores",
    kind: "source",
    x: 70,
    y: 250,
    description: "Operational databases replicated into the analytics estate.",
    tech: ["Oracle", "MS SQL", "PostgreSQL"],
  },
  {
    id: "src-events",
    label: "EVENTS",
    sublabel: "user & system activity",
    kind: "source",
    x: 70,
    y: 400,
    description: "Clickstreams, sensors and system telemetry arriving continuously.",
    tech: ["IoT", "Telemetry", "Logs"],
  },
  {
    id: "kafka",
    label: "KAFKA",
    sublabel: "stream ingestion",
    kind: "ingest",
    x: 275,
    y: 175,
    description: "Apache Kafka topics buffering real-time streams for downstream consumers.",
    tech: ["Apache Kafka", "Streaming", "Event-driven"],
  },
  {
    id: "etl",
    label: "ETL",
    sublabel: "batch pipelines",
    kind: "ingest",
    x: 275,
    y: 360,
    description: "Batch extraction and transformation with enterprise ETL tooling.",
    tech: ["Informatica", "Azure Data Factory", "IICS", "SSIS"],
  },
  {
    id: "databricks",
    label: "DATABRICKS",
    sublabel: "lakehouse processing",
    kind: "process",
    x: 490,
    y: 175,
    description: "Spark processing on the lakehouse — bronze to gold, batch and stream unified.",
    tech: ["Databricks", "PySpark", "Delta Lake", "Medallion"],
  },
  {
    id: "warehouse",
    label: "WAREHOUSE",
    sublabel: "modeled & governed",
    kind: "store",
    x: 490,
    y: 360,
    description: "Dimensional models and governed marts — the single source of truth.",
    tech: ["Data Warehousing", "SQL", "Dimensional Modeling"],
  },
  {
    id: "ml",
    label: "ML MODELS",
    sublabel: "train · track · explain",
    kind: "ml",
    x: 705,
    y: 130,
    description: "Models trained on curated data, tracked with MLflow, explained with SHAP.",
    tech: ["PyTorch", "scikit-learn", "MLflow", "SHAP"],
  },
  {
    id: "analytics",
    label: "ANALYTICS",
    sublabel: "BI & dashboards",
    kind: "serve",
    x: 705,
    y: 400,
    description: "Decision-ready dashboards and self-service analytics on governed data.",
    tech: ["Power BI", "Tableau", "SQL"],
  },
  {
    id: "serve",
    label: "APIS & APPS",
    sublabel: "products in prod",
    kind: "serve",
    x: 900,
    y: 265,
    description: "Predictions and data served through APIs and web products.",
    tech: ["Next.js", "REST APIs", "Node.js", "Azure"],
  },
  {
    id: "monitor",
    label: "OBSERVE",
    sublabel: "monitoring & alerts",
    kind: "observe",
    x: 900,
    y: 80,
    description: "Data quality checks, lineage and alerting across every stage.",
    tech: ["Data Quality", "CI/CD", "GitHub Actions"],
  },
];

export const pipelineLinks: PipelineLink[] = [
  { from: "src-api", to: "kafka" },
  { from: "src-events", to: "kafka" },
  { from: "src-db", to: "etl" },
  { from: "kafka", to: "databricks" },
  { from: "etl", to: "warehouse" },
  { from: "databricks", to: "warehouse" },
  { from: "databricks", to: "ml" },
  { from: "warehouse", to: "analytics" },
  { from: "ml", to: "serve" },
  { from: "analytics", to: "serve" },
  { from: "monitor", to: "databricks", kind: "observe" },
  { from: "monitor", to: "ml", kind: "observe" },
  { from: "monitor", to: "serve", kind: "observe" },
];
